import { globalFont } from "../config/fonts";
import "./globals.css";

export const metadata = {
  title: "Quiz & Membership",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={globalFont.className}>
        {children}
      </body>
    </html>
  );
}
