import { globalFont } from "../config/fonts";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Quiz & Membership",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={globalFont.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
